### ISSUE TITLE
Unable to show second and third line 

### ISSUE THREAD

**Issue by ooi19935566** [pcyuen98/python-intro#3]
import json

def loadJson():
    # some JSON:
    x =  '{ "name":"John", "age":30, "city":"New York"}'
    # parse x:
    y = json.loads(x)
    # the result is a Python dictionary:
    print(y["name"])
    return y["name"]

    print(y["age"])
    return y["age"]

    print(y["city"])
    return y[""]

**Comment by pcyuen98** [comment]
Hi, u can only have one return on each  method. In this case, your method or module is loadJson

import json

def loadJson():
# some JSON:
    x = '{ "name":"John", "age":30, "city":"New York"}'
# parse x:
    y = json.loads(x)
# the result is a Python dictionary:
    print(y["name"])
    return y["name"]

**Comment by pcyuen98** [comment]
working source code

import json

def loadJson():
# some JSON:
    x = '{ "name":"John", "age":30, "city":"New York"}'
# parse x:
    y = json.loads(x)
# the result is a Python dictionary:
    print(y["name"])
    return y["name"]
