### ISSUE TITLE
Function no printing accordingly 

### ISSUE THREAD

**Issue by ooi19935566** [pcyuen98/python-intro#8]
Expected result and actual result are different 

Code Below : 
#1 from method import sparePart, printHelloWorld
#2 print ('test sparePart method-->', printHelloWorld()) 

Actual result. 

test printHelloWorld method--> hello World
test sparePart method--> 2
Enter name:

**Comment by pcyuen98** [comment]
For a proper method handling, you need to define in a class.  

Example as below 
https://github.com/pcyuen98/python-intro/blob/main/src/cls/basic_call_method.py

New method_class.py been created to solve this. You may run a git pull
